### ISSUE TITLE
State of checks

### ISSUE THREAD

**Issue by sidey79** [CasperWA/push-protected#149]
Is it possible, to look at the status (failed, successfull, canceled) of status check, before the merge is done?

I want to disable the merge, if one of the checks has failed.

**Comment by CasperWA** [comment]
It should by default always disallow merging if a _required_ status check fails, since this is how protected branches work.

But do you mean to have more control over the merging depending on _any_ status check, also non-required status checks? Maybe even on a specific status check-level, i.e., if the "my custom check" status check fails, is cancelled or otherwise, the merge should be disabled?

Of course, it should be noted that if the PAT supplied to the action is for an admin, with force push rights and `force: true`, then the merge will happen no matter the result of the status checks. In this case it the merge could be avoided with what you suggest. Is this your use case?

**Comment by CasperWA** [comment]
@sidey79, please use the upcoming v2.15.0 to use the new `acceptable_conclusions` input (see [description in README](https://github.com/CasperWA/push-protected#inputs)) to check if this solves your use case.
