### ISSUE TITLE
feature request: don't wait for any checks

### ISSUE THREAD

**Issue by kevcube** [CasperWA/push-protected#226]
I'm using this with commits that have already passed checks, I don't want to wait for any checks to succeed, I only want to immediately push branch A to branch B once commits have been pushed to A.

**Comment by kevcube** [comment]
I was able to find an alternate workable solution [here](https://github.com/community/community/discussions/25305#discussioncomment-3247409)

If this request doesn't make sense in the context of this action feel free to close.

**Comment by CasperWA** [comment]
In this case, I think using `git push` straight up or the [ad-m/github-push-action](https://github.com/ad-m/github-push-action) action should do the trick, no? This action is mainly meant for pushing to protected branches where some (as yet unfinished) status checks are required to be able to push.

However, it may be that you're using other aspects of this action not available elsewhere? Like temporarily ignoring requiring reviews? The latter part can be remedied with the new protected branch settings GitHub have been introducing since this action was first created, and some other issues hint at this (#130, #191).

But I may (definitely) be missing some edge case where your use case is valid and the mixture of status checks versus GitHub protected branches falls between the cracks of what can be verified and the only solution is to use this action in place of other, more straight forward methods for pushing (at least implementation wise).

In the end, it seems there is something to be said for the workable solution you're presenting, which might be nice to document. I'm unsure exactly the context in which to document your solution, so feel free to contribute to the README or a write up here in the issue that I can add to the README, about the motivation of using the workable solution (i.e., the use case) and how to use it.
